name 'leds_handler'
maintainer 'Matt Ray'
maintainer_email 'matt@chef.io'
license 'Apache-2.0'
description 'Installs/Configures the LEDs handler for Raspberry Pi and similar devices'
version '0.2.2'
chef_version '>= 14.0'

supports 'centos'
supports 'debian'
supports 'raspbian'
supports 'redhat'
supports 'ubuntu'

issues_url 'https://github.com/mattray/leds_handler-cookbook/issues'
source_url 'https://github.com/mattray/leds_handler-cookbook'
